### ISSUE TITLE
Problem with save state n°39, part 7

### ISSUE THREAD

**Issue by nekmao33** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#17]
Two rooms before entering the Spear Pillar, there is two Team Galaxy members.
The first one is easily defeated but the 2nd one is never defeated.

On the first turn, Smurf is against a Glameow and uses Strength.
On the second turn, Smurf is against a Golbat and uses the same move. But, this move do not kill it (~20 % HP left), then Golduck is poisoned by the Golbat.

<img width="256" alt="2024-11-08_17h31_14" src="https://github.com/user-attachments/assets/0e1dd30e-e6c6-4a55-a05f-3b4233d790f5">

In the code, the fight should be over but this is not the case. The game can't continue.

There's the same issue with the following Galactic trainer.

https://drive.google.com/drive/folders/1MXC8x1-0pQKiUjXWmIuoozlPiOCLqiHk?usp=sharing

**Comment by KeeyanGhoreshi** [comment]
oh right, lol it's because strength and surf are mixed up.  This is because I'm being lazy with the patch, I should've just quashed this issue outright.  I will work on a fix and it will likely occur after `35-AfterGolduckDaycare`.  The order of moves gets messed up if golduck hits lvl 50 while training and I got lazy and didn't handle it correctly.  The fix is just to forcibly arrange golduck's moves at the move deleter, so not a big issue.  Thanks!

**Comment by KeeyanGhoreshi** [comment]
should be fixed with #19

**Comment by nekmao33** [comment]
That works. Thanks ! :)
