### ISSUE TITLE
Level up in a fight that wasn't supposed to

### ISSUE THREAD

**Issue by MegaJulien** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#2]
So after defeating Roark, i go to defeat the Grunts and after beating Glameow, Monferno level up to 19 but it's not something that was intented so the script lose track. I can always reproduce this scenario from the SaveState from defeating Roark. 

Here is the SaveState : https://files.catbox.moe/4b99w4.State 

I can see that at the end of the arena, Monferno has 9 exp left to level up. Maybe it's a very rare case or something to do with my emulation(it's possible, i ran into a lot of issues for the first script)

**Comment by KeeyanGhoreshi** [comment]
Interesting! The first script is a little iffy since it's the earliest one, so if there are bugs, they'll be there.  

Monferno is meant to hit 19 and learn flame wheel after defeating roark, and it _should_ be guarenteed. I'm unable to load your savestate to check myself, probably related to game version, but I can already guess what the issue is.  

Right before battling Roark you travel to the oreburgh gate to gather just a bit of XP there from battling a couple wild pokemon.  Two things could be happening, either I miscalculated the XP gain and the battles there don't provide enough to hit lvl 19 later, meaning I need to add in an extra wild battle there, or there's not enough spinning and one of those wild battles didn't happen.

It would be helpful to know some more details so I can pin down the issue.  What's monferno's XP at before battling Roark?

**Comment by KeeyanGhoreshi** [comment]
I'll also mention that I just checked the code and the amount of spins for the battles in oreburgh gate are definitely too low, I don't know how I didn't catch this before but 36*4 is not nearly enough steps to guarantee a wild battle in a cave, so that is certainly an issue.  So that is potentially your issue.  But if you did get two battles here and still ran into this problem, then there's an additional problem that there needs to be an extra battle to close an XP gap.

**Comment by MegaJulien** [comment]
I didn't really watch the farm so i can't say, it could also be earlier farm. I do have the earlier save and just before the fight of Roark, Monferno was at 3805 Exp, so 770 from next level. He was barely at 18.
![image](https://github.com/user-attachments/assets/3190d4e1-68bf-488b-b4f4-3d339907ad50)

After the first Training, chimchar was level 9 at 439 Exp.
After learning MachPunch, Monferno was level 14 at 1626 Exp, almost didn't make it to 14.

**Comment by KeeyanGhoreshi** [comment]
The most likely scenario here is that you missed the first or second wild battle in oreburgh gate.  1626xp is expected after the mach punch training, smack dab in the middle of the possible 0-23 discrepancy range.  3805 is about 40ish XP off from average, which is pretty close to the average you get from a battle in oreburgh gate.

The inputs only list a spin 144 steps, which isn't enough especially if you are using an emulator on default date settings, since they default to Jan 1st which is one of the decreased encounter dates.  

All this to say, thanks for bringing this to my attention, I'll fix those spin values.
