### ISSUE TITLE
"Chimchar did not learn Taunt."

### ISSUE THREAD

**Issue by Harpig** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#24]
So I decided to start over with all the latest fancy changes and already hit a bump in the road from the first script.
When training Chimchar to level 9, instead of stopping at the stopping rule and learning Taunt when we've synced up, SOUP decides to not learn Taunt and keep grinding past level 9 (stopping short 31 exp from lvl 10).
[States](https://github.com/user-attachments/files/17789585/Script1.zip)

**Comment by KeeyanGhoreshi** [comment]
I'm going to run a couple tests, but I suspect the issue here is that chimchar can hit level 9 in 12 battles, which is in the annotation but I probably goofed and made the cycle split 12/6 instead of 11/7, since the twelfth cycle could potentially level up and should be handled by the second version of the routine instead of the first.

**Comment by KeeyanGhoreshi** [comment]
Nevermind, the thing that I thought it was could be true still, but the actual issue is that in cases where chimchar is within 20-24 xp of level 9, the wait time after attacking is 5 frames too short and it misses its first B input.  Adding 5 extra frames of wait time fixes it but I'm going to just add more than that for some extra buffer.

**Comment by KeeyanGhoreshi** [comment]
this should be fixed, it looks like this is only an issue in `1.lua` (typical) since all the other stopping rules use the correct wait time of 1200+ already.

**Comment by Harpig** [comment]
It works, thanks 👍
