### ISSUE TITLE
Entered Roark fight at lv17

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#25]
Managed to catch the last few minutes before the Roark fight in my most recent playthrough. Unsure why, but the 2 wild pokemon encounters weren't enough to reach level 18.

During the fight itself, Monferno ended up using Return instead of Mach Punch vs Onix & Cranidos.

Luckily the script was able to beat the fight and progress, despite this issue, however I can imagine that seeds with multiple crits might have had a bad time

this is my [Roark fight Savestate.txt](https://github.com/user-attachments/files/17792164/Roark.fight.Savestate.txt) as a txt, since .state files won't attach cleanly (idk github has always been so counterintuitive for me)

**Comment by KeeyanGhoreshi** [comment]
I thought I had fixed this issue, if you're able to put the state files in a google drive or zip folder, you should be able to upload them.

**Comment by Pulse-kS** [comment]
[Pokemon - Platinum Version (USA) (Rev 1).MelonDS.QuickSave1.zip](https://github.com/user-attachments/files/17792202/Pokemon.-.Platinum.Version.USA.Rev.1.MelonDS.QuickSave1.zip)
was only a manual savestate during the fight where I'd noticed, but one thing I'm realising is that during those last wild encounters, SOUP was spinning in the move select menu, rather than the fight/bag/run menu, indicating that there may have been a 1-input desync caused somewhere else.

**Comment by KeeyanGhoreshi** [comment]
It will not surprise me if there are not enough b inputs to handle certain cases.  This is a common issue in `1.lua`, I didn't leave enough buffer for a lot of things.  If you have the `18-BeforeTraining` savestate, that should shed some light on this.

**Comment by Pulse-kS** [comment]
Ah, I see the save folder now
[Script1.zip](https://github.com/user-attachments/files/17792216/Script1.zip)
Included a couple before & after just for the sake of things.

**Comment by KeeyanGhoreshi** [comment]
Thanks, there's an issue here with the xp gain from low-rolling 2 lvl 5 zubats on a seed that has also received the least possible xp from the prior stopping rule (or close to it).  This should have a relatively simple fix,

**Comment by KeeyanGhoreshi** [comment]
Should be fixed now.  Monferno using return on onix/cranidos is likely related to unexpected level up prompt after geodude.  The spinning on the move screen instead of the fight/bag screen is actually probably related to user error, clicking on the emulator window while it is spinning during that training session, which triggers a touch input centered on wherever the last touch input was.

The reason I say this is because I actually did the exact same thing while testing this section, causing the same problem, and I can't find any other way you'd end up spinning in the move selection menu.
