### ISSUE TITLE
Desync at Wake

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#29]
Woke up to the game in this state, just as it made the after-saturn savestate in script 7.
Tracing it back, looks like the desync happened somewhere in early script 5, this time before the crasher wake fight.
Wish I could tell you the cause, but once again I wasn't there for it. However I am using the latest version (replay was run at 4x speed)
![image](https://github.com/user-attachments/assets/a35a3a0c-0cb4-41c7-89a2-ba0e84c3f8b3)
[Script5 early saves.zip](https://github.com/user-attachments/files/17876396/Script5.early.saves.zip)
let me know if you need earlier savestates

**Comment by KeeyanGhoreshi** [comment]
huh... it's like a couple frames off on the first right input after the rival battle, so it just barely misses it and doesn't move.

**Comment by KeeyanGhoreshi** [comment]
oh it looks like if flame wheel crits the "it's a critical hit!" message adds just a couple frames of time, and the timing on the movement after the rival battle is super tight for no reason.  I am endlessly plagued by my past self's decision not to just pad in extra B inputs everywhere...

Thanks for the report, this is fixed with a couple extra B inputs (or just by waiting an extra second).
