### ISSUE TITLE
Script4 - never made it to daycare -> started double battle

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#30]
feels like every other day I pop in here - hi again!
Woke up to see very long spinning inputs during this trainer fight, which made me think that SOUP was looking for hippopotas, 
![image](https://github.com/user-attachments/assets/87a2dfb2-e923-446b-9e03-0b2df8b9d6d4)
Upon further investigation, looks like the desync started between 10-BeforeMail and 11-InDaycare. As that savestate has SOUP standing in front of the Lost Tower.
Due to that desync, we eventually bumped into the roaming double battle immediately next to the lost tower, which is where we got stuck
[Script4 00-14.zip](https://github.com/user-attachments/files/17882549/Script4.00-14.zip)

**Comment by KeeyanGhoreshi** [comment]
looks like the core issue here is that the repel from catching roselia runs out too soon and isn't accounted for.  That's an easy enough fix, it just needs to account for the extra step from the repel.

The background is that the repel isn't supposed to be unaccounted for here.  In fact, there's almost no way this issue would have made it through testing (because it would either occur every time or never).  It looks like my recent changes have introduced some slight variance in timing, and now instead of this never being an issue (for morning seeds that fight the joggers), it's now always an issue.  

I probably should have tested that change in a morning seed!  Thanks for the report, this should be fixed by the recent commit.
