### ISSUE TITLE
Desync in Old Chateau

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#32]
seems like every day I come back with a desync earlier in the sequence - I swear one day I'll get a successful run.
Watched gastly get caught and named, however noticed soup started running into walls within the chateau -> start spinning inplace with a repel active within the old chateau, with the latest savestate indicating it thought it was starting the Eevee training sequence to Lv29
![image](https://github.com/user-attachments/assets/1109168d-9fd4-48ef-af36-19a4e736ae5e)
[Chateau.zip](https://github.com/user-attachments/files/17898793/Chateau.zip)
My guess is that repel ran out and we got an encouter within the chateau, because I can see that the exp values are different between 10-CaughtGastly and 11-ReadyForTraining

**Comment by KeeyanGhoreshi** [comment]
you seem to be a magnet for this type of stuff!  Thanks for persevering.  This one is actually quite interesting, in the Old Chateau you can occasionally get a "special event" when entering this dining hall where the "ghost" of an old man appears, and flies off to the left of the screen.  Apparently it is not just solved by waiting for it to be over, I didn't realize that your character actually turns to the left to look at the ghost while it flies off.  This forced turning makes the first left input take a step instead of turn to face left, which causes this desync.  I will push up a fix for this shortly.

**Comment by Pulse-kS** [comment]
I did actually see that event happen! Didn't realise that it was the cause of the desync when it happened, but I guess I actually caught this one live for once

**Comment by Pulse-kS** [comment]
gotta say - thanks for being so punctual with all these patches & updates. Really nice getting to catch things, and then know I can just wait for a patch before trying again. And I learn a new thing about the run with each report, so thats a bonus.

**Comment by KeeyanGhoreshi** [comment]
Of course, I generally have the sequence running as well as I try to patch out the last of these bugs.  Most of my runs have been successful recently, so we should be reaching a point of stability while closing out these issues.
